# -------------------------------------------------------------------------------------
#
# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

parameters:
  - name: ACTION
    displayName: 'Pipeline Action'
    type: string
    values:
      - 'CREATE'
      - 'DELETE'

trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  - group: ohc-stage-bastion-var-group

resources:
  repositories:
    - repository: templates
      type: github
      name: MadhurangaWije/my-pipeline-templates
      ref: refs/heads/main
      endpoint: $(GITHUB_SERVICE_ENDPOINT)

jobs:
  - job: create_azure_bastion_service
    displayName: Create Azure Bastion Service
    condition: eq('${{ parameters.ACTION }}', 'CREATE')
    steps:
      - template: cd-pipelines/templates/add-bastion-service.yaml@templates
        parameters:
          BASTION_SERVICE_NAME: $(NAME)
          PUBLIC_IP_ADDRESS: $(PUBLIC_IP_ADDRESS)
          RESOURCE_GROUP: $(RESOURCE_GROUP)
          VNET_NAME: $(VIRTUAL_NETWORK)
          LOCATION: $(LOCATION)
          AZURE_RM_SERVICE_CONNECTION: $(AZURE_RM_SERVICE_CONNECTION)

  - job: delete_azure_bastion_service
    displayName: Delete Azure Bastion Service
    condition: eq('${{ parameters.ACTION }}', 'DELETE')
    steps:
      - template: cd-pipelines/templates/delete-bastion-service.yaml@templates
        parameters:
          BASTION_SERVICE_NAME: $(NAME)
          RESOURCE_GROUP: $(RESOURCE_GROUP)
          AZURE_RM_SERVICE_CONNECTION: $(AZURE_RM_SERVICE_CONNECTION)
