# -------------------------------------------------------------------------------------
#
# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

parameters:
  - name: ACTION
    displayName: 'Pipeline Action'
    type: string
    values:
      - 'CREATE'
      - 'DELETE'
  - name: BASTION_SERVICE_NAME
    displayName: 'Bastion Service Name'
    type: string
  - name: PUBLIC_IP_ADDRESS
    displayName: 'Azure Public IP Address'
    type: string
  - name: RESOURCE_GROUP
    displayName: 'Resource Group'
    type: string
  - name: VNET_NAME
    displayName: 'Virtual Network Name'
    type: string
  - name: LOCATION
    displayName: 'Location'
    type: string
  - name: AZURE_RM_SERVICE_CONNECTION
    displayName: 'Azure Resource Manager Service Connection'
    type: string
  - name: PIPELINE_TEMPLATE_DIR
    type: string
    default: '../pipeline-templates'

resources:
  repositories:
    - repository: templates
      type: github
      name: MadhurangaWije/MadWorks
      ref: refs/heads/master
      endpoint: ohc-github

jobs:
  - job: create_azure_bastion_service
    displayName: Create Azure Bastion Service
    condition: eq('${{ parameters.ACTION }}', 'CREATE')
    steps:
      - template: 'pipeline-template/azure/bastion/add-bastion-service.yaml@templates'
        parameters:
          BASTION_SERVICE_NAME: ${{ parameters.BASTION_SERVICE_NAME }}
          PUBLIC_IP_ADDRESS: ${{ parameters.PUBLIC_IP_ADDRESS }}
          RESOURCE_GROUP: ${{ parameters.RESOURCE_GROUP }}
          VNET_NAME: ${{ parameters.VNET_NAME }}
          LOCATION: ${{ parameters.LOCATION }}
          AZURE_RM_SERVICE_CONNECTION: ${{ parameters.AZURE_RM_SERVICE_CONNECTION }}

  - job: delete_azure_bastion_service
    displayName: Delete Azure Bastion Service
    condition: eq('${{ parameters.ACTION }}', 'DELETE')
    steps:
      - template: '${{ parameters.PIPELINE_TEMPLATE_DIR }}/azure/bastion/delete-bastion-service.yaml'
        parameters:
          BASTION_SERVICE_NAME: ${{ parameters.BASTION_SERVICE_NAME }}
          RESOURCE_GROUP: ${{ parameters.RESOURCE_GROUP }}
          AZURE_RM_SERVICE_CONNECTION: ${{ parameters.AZURE_RM_SERVICE_CONNECTION }}
