#-------------------------------------------------------------------------------------
#
# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

parameters:
  - name: PARAM_1
    type: string

jobs:
  - job: tests_1
    displayName: 'Test Pipeline'
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: <Name of the Azure Resource Manager service connection>
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az network bastion create --name ohc-stage-bastion --public-ip-address ohc-stg-bastion-public-ip --resource-group openhealthcare-stage --vnet-name ohc-stage-bastion-vnet --location eastus2