#-------------------------------------------------------------------------------------
#
# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

parameters:
  - name: ACTION
    type: string

jobs:
  - job: CreateBastion
    displayName: 'Bastion Create Pipeline'
    condition: eq('${{ parameters.ACTION }}', 'CREATE')
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: ohc-stage-azurerm-service-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az network bastion create --name ohc-stage-bastion --public-ip-address ohc-stg-bastion-public-ip --resource-group openhealthcare-stage --vnet-name ohc-stage-virtual-network --location eastus2
  - job: DeleteBastion
    displayName: 'Bastion Delete Pipeline'
    condition: eq('${{ parameters.ACTION }}', 'DELETE')
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: ohc-stage-azurerm-service-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az network bastion delete --name ohc-stage-bastion --resource-group openhealthcare-stage